[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "friendtina129", email = "64568115+friendtina129@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.62.0",
]

[project.scripts]
myproject = "myproject:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
